name: Build and Release

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --ignore-engines

    - name: Get latest tag
      id: get_latest_tag
      run: |
        git fetch --tags
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

    - name: Generate new version
      id: new_version
      run: |
        latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
        major=$(echo $latest_tag | cut -d. -f1 | tr -d 'v')
        minor=$(echo $latest_tag | cut -d. -f2)
        patch=$(echo $latest_tag | cut -d. -f3)
        new_patch=$((patch + 1))
        new_version="v$major.$minor.$new_patch"
        echo "new_version=$new_version" >> $GITHUB_OUTPUT

    - name: Create new tag
      run: |
        git config --local user.email "bao.lq@holistics.io"
        git config --local user.name "baolequoc"
        git tag ${{ steps.new_version.outputs.new_version }}
        git push origin ${{ steps.new_version.outputs.new_version }}

    - name: Build for macOS
      run: yarn electron:build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: release/
        if-no-files-found: error

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.new_version.outputs.new_version }}
        files: |
          release/**/*.dmg
          release/**/*.AppImage
          release/**/*.exe
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}