name: Build and Test

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --ignore-engines

    - name: Build
      run: yarn electron:build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: release/
        if-no-files-found: error